/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingRouteImport } from './routes/wedding'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const WeddingRoute = WeddingRouteImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/wedding': typeof WeddingRoute
  '/product/$handle': typeof ProductHandleRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/wedding': typeof WeddingRoute
  '/product/$handle': typeof ProductHandleRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/wedding': typeof WeddingRoute
  '/product/$handle': typeof ProductHandleRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/wedding'
    | '/product/$handle'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/wedding'
    | '/product/$handle'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/wedding'
    | '/product/$handle'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  WeddingRoute: typeof WeddingRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding': {
      id: '/wedding'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  WeddingRoute: WeddingRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
